name: tamer-university
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.7
  - pytorch=1.8.1
  - torchvision=0.9.1
  - cudatoolkit=11.1
  - pillow=8.4.0
  - pytorch-lightning=1.4.9
  - torchmetrics=0.6.0
  - pip
  - pip:
      - -e .
